### PR TITLE
Added i18n support and spanish translation

### PR DESCRIPTION
**Pull request by ajerez**
🙂🇪🇸

### CODE REVIEW

**Comment by pnevares** [comment]
I love this idea!

A `package-lock.json` was included in this PR, looks like `yarn.lock` is the file in use for this project.

**Comment by ajerez** [comment]
> I love this idea!
> 
> A `package-lock.json` was included in this PR, looks like `yarn.lock` is the file in use for this project.

Fixed, thanks :)

**Comment by sdras** [comment]
I love this :) A couple of questions:

- I didn't see an implementation of a language switcher. Am I blind and missing it (totally possible) or has it not been implemented again (I don't mind doing it myself if so)
- I need to update some of the text in the explanation. Would you prefer I do this now, before this is merged, or would it be better for you after and then you submit another PR? Are you ok with maintaining the Spanish version moving forward?

Thanks!

**Comment by ajerez** [comment]
> I love this :) A couple of questions:
> 
> * I didn't see an implementation of a language switcher. Am I blind and missing it (totally possible) or has it not been implemented again (I don't mind doing it myself if so)
> * I need to update some of the text in the explanation. Would you prefer I do this now, before this is merged, or would it be better for you after and then you submit another PR? Are you ok with maintaining the Spanish version moving forward?
> 
> Thanks!

Yes, sorry, the code loads the app with your browser language but there is no language selector.

 I've updated the PR with the translation for the new Screenreaders note and the last PRs texts. 
Of course I'd be glad to maintaining the spanish version :)

**Comment by trickstival** [comment]
That's super cool. Once it's approved I can help with a portuguese translation

**Comment by sdras** [comment]
Great! Let's do this 🤘

**Pull request merged**
