### PR TITLE
remove divs with shift-click

### PR DESCRIPTION
**Pull request by sjconnor**
The only way to remove divs seemed to be with a page refresh.
This modification allows the user to do a shift-click to remove divs one by one.

### CODE REVIEW

**Comment by pnevares** [comment]
Looks like this works great with items within a single column and row!

It doesn't appear to remove grid items that span multiple columns or rows. Checked it out using the deploy preview above.

**Comment by sjconnor** [comment]
@pnevares you're right - I was neglectful to not say so. 

I'm not in a position to extend it to include divs that span cols/rows at the moment, but if the PR is helpful and accepted as is, I'd work on it and hopefully be able to submit another PR to address that.

**Comment by pnevares** [comment]
Looks like I was just impatient, if you continue to hold down <kbd>Shift</kbd> for some time after mouseup the multi-row/column grid items do get removed.

I tried attaching this to mousedown instead and it worked reliably in both situations, here's an example if you'd like to try it out:

```js
if (startend === "s") {
  this.child.remove = event.shiftKey;
}

//create the children css units as a string
if (startend === "e") {
  let childstring = `${this.child.srow} / ${this.child.scol} / ${this
    .child.erow + 1} / ${this.child.ecol + 1}`;

  if (this.child.remove) {
    this.$store.commit("removeChildren", childstring);
  } else {
    this.$store.commit("addChildren", childstring);
  }
}
```

**Comment by nhoizey** [comment]
This feature (removing a div) is needed, but how would this implementation work on a touch screen (tablet for example)?

**Comment by sdras** [comment]
Hey! Thanks for your work on this but another PR was more of what I think people are looking for here. Thanks though!

**Pull request closed without merging**
