### PR TITLE
Added portuguese language

### PR DESCRIPTION
**Pull request by trickstival**
Now folks from Brazil and Portugal (or any country that speaks Portuguese...) can have this website in their native language!

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey!

I have been assigned as the Portuguese human on this PR 👋

I have a question, why is the grid a he? I feel like it fits more to be a she or just remove the pronoun completely.

Is that okay?

**Comment by trickstival** [comment]
You have a point there.

If you check in the end of the file I use it as "she" too, but it's probably better to use it as "she" everywhere. I'm gonna correct it.

**Comment by SaraVieira** [comment]
Awesome!

Obrigado! After that all looks 💯  to me @sdras

**Comment by trickstival** [comment]
@SaraVieira done!

**Comment by sdras** [comment]
Thank you!

**Comment by SaraVieira** [comment]
🎉

**Pull request merged**
